FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

# Install required packages
RUN apt-get update && \
        apt-get install -y --no-install-recommends \
         ca-certificates \
         curl \
         jq \
         git \
         iputils-ping \
         netcat \
         unzip \
         awscli \
         software-properties-common \
         gnupg

RUN apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7EA0A9C3F273FCD8 && \
         add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && \
         apt update && \
         apt-cache policy docker-ce && \
         apt install docker-ce -y

# Clean system
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
